title: Documentation Minimal Theme
lead: Strait to the docs, clean markdown theme
description: >-
  Minimalistic and clean documentation theme aiming
  to minimalize differences between your repo
  documentation and the rendered one.
copyright: Copyright &copy; 2020 Lorem Ipsum Inc.  All rights reserved.

plugins:
  - jekyll-seo-tag